The first task
sergey-berezin/s02170686 pull request #1
Opened 2020-09-27 20:33 UTC by TimSyn

Здравствуйте! Сдаю первое задание)

2020-10-05 08:55 UTC, sergey-berezin requested changes

2020-10-05 08:55 UTC, sergey-berezin commented on NNLib/NNP.cs
> +                Console.WriteLine($"{Thread.CurrentThread.Name}: image \"{Path.GetFileName(name)}\" is {res}");
Должен быть механизм передачи информации в приложение-потребитель.

2020-10-05 08:55 UTC, sergey-berezin commented on NNLib/NNP.cs
> +            return list_of_labeled_images;
Результаты распознавания доступны только после завершение распознавания всех изображений.

2020-10-25 20:52 UTC, TimSyn commented
Здравствуйте, Сергей Борисович! Прошу прощения, что так поздно. Я не сразу понял схему с pull request и подумал, что вы зачли работу прям во время практику, поэтому, не знаю почему, оставлю изменения до пуша вместе со вторым заданием. Соотвественно, также добавил пользовательский интерфейс. Еще раз прошу прощения.

2020-11-02 08:00 UTC, sergey-berezin approved these changes

2020-11-02 08:00 UTC, merged